# Generated by Django 6.0.6 on 2026-06-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
