# Generated by Django 6.0.6 on 2026-06-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('person1', 'Person 1'), ('person2', 'Person 2')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='profile/')),
                ('description', models.TextField()),
            ],
        ),
    ]
