# Generated by Django 6.0.6 on 2026-06-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bio',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bio',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bio',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
