# Generated by Django 6.0.6 on 2026-06-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('person1', 'Person 1'), ('person2', 'Person 2')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('skill_type', models.CharField(choices=[('technical', 'Technical'), ('professional', 'Professional')], max_length=20)),
                ('proficiency', models.IntegerField(default=80)),
            ],
        ),
    ]
